version: "3.9"

services:
  
  project_database:
    image: mysql:latest
    container_name: project_database
    restart: always
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - ./mysql_data/superafm.sql:/docker-entrypoint-initdb.d/superafm.sql
    environment:
      - MYSQL_DATABASE=golang_test
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=1234
    
  project_server:
    build: .
    container_name: project_server
    depends_on:
      - project_database
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - my-server:/app  
volumes:
  my-db:
  my-server:

networks:
  backend:
