version: "3.3"

services:
  
  project_database:
    image: mysql:latest
    container_name: project_database
    restart: always
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - ./mysql_data/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_DATABASE=golang_test
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=1234
    
  project_server:
    image: angelosanag/project_server
    container_name: project_server
    depends_on:
      - project_database
    ports:
      - 8080:8080
    networks:
      - backend

  python_service:
    image: angelosanag/python_service
    container_name: python_service
    depends_on:
      - project_database
    ports:
      - 5000:5000
    networks:
      - backend
volumes:
  my-db:

networks:
  backend:
